# Generated by Django 3.1.4 on 2021-01-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201214_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=120, null=True)),
                ('username', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('pass1', models.CharField(max_length=120, null=True)),
                ('pass2', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
