# Generated by Django 3.1.4 on 2021-02-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
